Master
IKSANOVA/Python_pr pull request #3
Opened 2021-08-28 10:55 UTC by IKSANOVA

2021-08-28 10:57 UTC, IKSANOVA commented
merge

2021-08-28 11:12 UTC, IKSANOVA commented
fix

2021-09-02 12:38 UTC, ketzhen requested changes
Хорошо, поправь немного и вливай в main

2021-09-02 12:38 UTC, ketzhen commented on test_auth2.py
> +        button = browser.find_element_by_css_selector("[name='test'] + button").click()
Вот тут нет смысла записывать в переменную, если ты сразу кликаешь.

2021-09-02 12:38 UTC, ketzhen commented on test_auth2.py
> +        print(welcome_text)
Принт не нужен)

2021-09-02 12:38 UTC, ketzhen commented on test_auth2.py
> +        assert element_is_present(browser, By.CSS_SELECTOR, ".notification.is-success"), "Верно"
А вот эта строка зачем? Выше уже есть проверка)

2021-09-02 12:38 UTC, ketzhen commented on test_auth2.py
> +from selenium.webdriver import Chrome
Я бы засунула все тесты по этому уроку в один файл, будет проще.

2021-09-02 12:38 UTC, ketzhen commented on test_menu.py
> +        assert menu_list == ['Поля ввода и кнопки', 'Мой питомец', 'О себе', 'Загрузка файла', 'Ожидание', 'Медленная загрузка', 'Модальные окна', 'Новая вкладка', 'iframe', 'Drag-and-drop']
Тут получается слишком длинная строка, лучше поправить форматирование.

2021-09-02 12:38 UTC, ketzhen commented on test_my_pets.py
> +        conf = browser.find_element_by_css_selector("button").click()
Тут не надо записывать в переменную, если кликаешь сразу

2021-09-02 12:38 UTC, ketzhen commented on test_my_pets.py
> +        assert element_is_present(browser, By.CSS_SELECTOR, ".notification.is-success"), "Успех"
Тут тоже лишняя строка, она же была у тебя выше.

2021-09-02 12:38 UTC, ketzhen commented on test_my_pets_no.py
> +        print(no_text)
Убери принт.

2021-09-02 12:38 UTC, ketzhen commented on test_my_pets_no.py
> +        conf = browser.find_element_by_css_selector("button").click()
Не надо записывать в переменную, если сразу кликаешь.

2021-09-05 19:22 UTC, merged