ref
IKSANOVA/Python_pr pull request #4
Opened 2021-09-12 09:55 UTC by IKSANOVA

2021-09-15 12:57 UTC, ketzhen requested changes
Нужно поправить везде то, что написала в 1 комментарии - оно в каждом тесте. После правки кидай на перепроверку, подниму балл :)

2021-09-15 12:57 UTC, ketzhen commented on auth.py
> +        wait_until_clickable(browser, By.NAME, 'email')
У тебя одна и та же ошибка получается по всему пуллреквесту - функция wait_until_clickable уже возвращает нужный нам элемент, и использует ожидание, то есть в тесте не надо еще раз создавать объект класса WebDriverWait и искать элемент с помощью find_element, так что меняем вот это все:
```
wait = WebDriverWait(browser, 10)
wait_until_clickable(browser, By.NAME, 'email')
browser.find_element(By.NAME, "email").send_keys("qa_test@test.ru")
wait_until_clickable(browser, By.NAME, 'password')
browser.find_element(By.NAME, "password").send_keys("!QAZ2wsx")
wait_until_clickable(browser, By.CLASS_NAME, 'button')
browser.find_element(By.CLASS_NAME, "button").click()
```

на:
```
wait_until_clickable(browser, By.NAME, 'email').send_keys("qa_test@test.ru")
wait_until_clickable(browser, By.NAME, 'password').send_keys("!QAZ2wsx")
wait_until_clickable(browser, By.CLASS_NAME, 'button').click()
```
В остальных местах тоже, надо убрать лишние моменты

2021-09-15 12:57 UTC, ketzhen commented on functions.py
> +    wait = WebDriverWait(browser, 10)
Убрать лишнее

2021-09-15 12:57 UTC, ketzhen commented on functions.py
> +def success_alert_is_present(driver: Chrome, timeout=5) -> bool:
Тут надо мою опечатку поправить, оно возвращает -> None

2021-09-15 12:57 UTC, ketzhen commented on test_about_my.py
> +        name = browser.find_element_by_name('name').send_keys("Лилия")
Тут везде надо добавить ожидания + не надо записывать в переменную` name = browser.find_element_by_name('name').send_keys("Лилия")` - он запишет то что вернет send_keys, то есть None, в этом нет смысла

2021-09-15 12:57 UTC, ketzhen commented on test_about_my.py
> +        login(browser)
Надо добавить ожидания

2021-09-15 12:57 UTC, ketzhen commented on test_auth.py
> +        wait = WebDriverWait(browser, 10)
Убери лишнее

2021-09-15 12:57 UTC, ketzhen commented on test_auth2.py
> +        wait = WebDriverWait(browser, 10)
Убери лишнее

2021-09-15 12:57 UTC, ketzhen commented on test_auth2.py
>          welcome_text = browser.find_element_by_css_selector(".notification.is-success").text
тут лучше искать с ожиданием видимости

2021-09-15 12:57 UTC, ketzhen commented on test_menu.py
> +        wait = WebDriverWait(browser, 10)
Убери лишнее

2021-09-15 12:57 UTC, ketzhen commented on test_menu.py
>          for element in browser.find_elements_by_css_selector('li a.navbar-item'):
Тут лучше искать с ожиданием видимости (в ec есть условие для видимости нескольких элементов)

2021-09-15 12:57 UTC, ketzhen commented on test_my_pets.py
> +        wait = WebDriverWait(browser, 10)
Убери лишнее

2021-09-15 12:57 UTC, ketzhen commented on test_my_pets.py
>          good_text = browser.find_element_by_css_selector(".notification.is-success").text
Лучше дождаться видимости

2021-09-15 12:57 UTC, ketzhen commented on test_my_pets_no.py
> +        wait = WebDriverWait(browser, 10)
Убери лишнее

2021-09-15 12:57 UTC, ketzhen commented on test_my_pets_no.py
>          no_text = browser.find_element_by_css_selector(".notification.is-danger").text
Добавить ожидание видимости

2021-09-15 12:57 UTC, ketzhen commented on test_wait.py
> +        wait = WebDriverWait(browser, 10)
Убери лишнее

2021-09-15 12:57 UTC, ketzhen commented on test_wait.py
> +        assert success_alert_is_present != "Успех!", "Неверный текст уведомления"
У тебя это не сработает, так как success_alert_is_present не возвращает ничего, убери assert (а то тут всегда assert None по сути)

2021-09-15 12:57 UTC, ketzhen commented on test_wait.py
> +        assert not element_is_present(browser, By.CSS_SELECTOR, ".notification.is-success"), "Сообщение Успех отсутствует"
Тут лучше добавить маленький таймаут (а не 10), как я на уроке показывала (переписать функцию чуток)

2021-09-15 12:57 UTC, ketzhen commented on test_wait.py
> +        browser.find_element_by_css_selector('[id="text_input"]').send_keys('qa_test@test.ru')
Убери лишнее

2021-09-15 12:57 UTC, ketzhen commented on test_wait.py
> +        wait = WebDriverWait(browser, 5)
Убери лишнее

2021-09-15 12:57 UTC, ketzhen commented on test_wait.py
> +        wait.until(title_is('Course Test Stand'))
Тут нужно условие заголовка из ec)

2021-09-18 14:16 UTC, IKSANOVA commented on functions.py
> +def success_alert_is_present(driver: Chrome, timeout=5) -> bool:
поправила

2021-09-18 14:16 UTC, IKSANOVA commented on auth.py
> +        wait_until_clickable(browser, By.NAME, 'email')
поправила

2021-09-18 14:25 UTC, merged